<?php
$data = array (
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '家用电器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '26',
    'name' => '家用电器',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '大家电',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '27',
    'name' => '大家电',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '平板电脑',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '28',
    'name' => '平板电脑',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '冰箱3',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '32',
    'name' => '冰箱3',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '家用空调',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '29',
    'name' => '家用空调',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '家电配件',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '30',
    'name' => '家电配件',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '洗衣机',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 2,
    'id' => '31',
    'name' => '洗衣机',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => 'test',
    'measure_unit' => '100',
    'parent_id' => '31',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '33',
    'name' => 'test',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '数码时尚',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '25',
    'name' => '数码时尚',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '智能硬件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '18',
    'name' => '智能硬件',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '移动电源',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '22',
    'name' => '移动电源',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '手机类型',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '手机类型',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '小型手机',
    'measure_unit' => '臺',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '3',
    'name' => '小型手机',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '3G手机',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '4',
    'name' => '3G手机',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '手机',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '3',
    'level' => 0,
    'id' => '6',
    'name' => '手机',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '电池',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '电池',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '耳机',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '8',
    'name' => '耳机',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '配件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '10',
    'level' => 0,
    'id' => '19',
    'name' => '配件',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '数码时尚',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '24',
    'name' => '数码时尚',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '保护壳',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '20',
    'name' => '保护壳',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '服装',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 0,
    'id' => '16',
    'name' => '服装',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '充值卡',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '12',
    'name' => '充值卡',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '小米手机',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '99',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 0,
    'id' => '86',
    'name' => '小米手机',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '家有在线',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '99',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '87',
    'name' => '家有在线',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '网点商品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '99',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '84',
    'name' => '网点商品',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => 'NBA',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '99',
    'has_children' => '1',
    'goods_num' => '1',
    'level' => 0,
    'id' => '88',
    'name' => 'NBA',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '湖人',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '99',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '89',
    'name' => '湖人',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '微门店商品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '99',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 0,
    'id' => '85',
    'name' => '微门店商品',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '微商城商品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '99',
    'has_children' => '1',
    'goods_num' => '3',
    'level' => 0,
    'id' => '82',
    'name' => '微商城商品',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '玻璃杯',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '99',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '90',
    'name' => '玻璃杯',
  ),
);
?>